const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'../..');
const html=fs.readFileSync(path.join(root,'vendor/MeshCore/examples/companion_radio/RepeaterMonitorPage.html'),'utf8');
assert(html.includes('id="credentials" data-manage hidden'));assert(html.includes('type="password"'));assert(html.includes('id="repeaterlist" data-manage hidden'));assert(html.includes('<th data-manage hidden>Check</th>'));
let script=html.split('<script>')[1].split('</script>')[0];
script=script.replace('refresh();setInterval(refresh,10000);','');
function element(){return {children:[],hidden:false,disabled:false,append(...x){this.children.push(...x)},replaceChildren(){this.children=[]},setAttribute(){}};}
const els=new Map(),managed=Array.from({length:7},element);let requests=0;
const sandbox={document:{getElementById(id){if(!els.has(id))els.set(id,element());return els.get(id)},createElement:element,querySelectorAll(){return managed}},window:{addEventListener(){}},fetch:async()=>{requests++;return {ok:true,json:async()=>({})}},console};
vm.createContext(sandbox);vm.runInContext(script,sandbox);
(async()=>{
 vm.runInContext('state={canManage:false,running:false,timeReady:true,storageOK:true,manualReady:true};buttons();',sandbox);
 assert(managed.every(e=>e.hidden)); assert(els.get('check').disabled);assert(!els.get('guestexport').hidden);
 await assert.rejects(vm.runInContext('api("/api/check",{})',sandbox),/read-only/);assert.equal(requests,0);
 await assert.rejects(vm.runInContext('api("/api/password",{all:true,password:"test-only"})',sandbox),/read-only/);
 await assert.rejects(vm.runInContext('api("/api/sync-time",{key:"01"})',sandbox),/read-only/);
 assert.equal(requests,0);
 els.get('repeaterpassword').value='test-only';vm.runInContext('buttons()',sandbox);assert.equal(els.get('repeaterpassword').value,'');
 await vm.runInContext('api("/api/state")',sandbox);assert.equal(requests,1);
 vm.runInContext('state.canManage=true;buttons();',sandbox);assert(managed.every(e=>!e.hidden));assert(!els.get('check').disabled);assert(els.get('guestexport').hidden);
 await vm.runInContext('api("/api/check",{})',sandbox);assert.equal(requests,2);
 vm.runInContext('state.clockSyncRunning=true;buttons()',sandbox);assert(els.get('check').disabled);assert(els.get('passwordsave').disabled);
 vm.runInContext('state.clockSyncRunning=false;',sandbox);
 vm.runInContext('state.neighbors=[];renderNeighbors();',sandbox);
 assert(!els.get('neighborsempty').hidden && els.get('neighborstable').hidden);
 vm.runInContext('state.neighbors=[{name:"Older",keyPrefix:"aaaa",rssi:-110,snr:-1.25,samples:16,ageSeconds:3600},{name:"<b>Fresh</b>",keyPrefix:"bbbb",rssi:-95,snr:4.75,samples:2,ageSeconds:8}];renderNeighbors();',sandbox);
 const rows=els.get('neighbors').children;
 assert.equal(rows.length,2);assert.equal(rows[0].children[0].children[0].textContent,'<b>Fresh</b>');
 assert.equal(rows[0].children[1].textContent,'-95 dBm');assert.equal(rows[1].children[2].textContent,'-1.25 dB');
 assert.equal(rows[0].children[3].textContent,'8s ago');assert.equal(rows[1].children[3].textContent,'1h ago');
 vm.runInContext('drawOverview=()=>{};state={canManage:false,repeaters:[{key:"a".repeat(64),name:"FlexSolar",enabled:true,lastSynced:0,clockCheckedAt:2000000000,clockOffset:12,clockUncertainty:34,readings:[]}],neighbors:[],timeReady:true,storageOK:true,manualReady:true};render();',sandbox);
 const clockCell=els.get('readings').children[0].children[4];
 assert.equal(clockCell.children[0].textContent,'≈ +12s ±34s');
 assert.equal(clockCell.children[1].textContent,vm.runInContext('date(2000000000)',sandbox));
 assert(els.get('readings').children[0].children[2].hidden);
 vm.runInContext('state.repeaters[0].readings=[{timestamp:2000000100,status:"ok",millivolts:4000,clockKnown:true,clockOffset:-4,clockUncertainty:2}];render();',sandbox);
 assert.equal(els.get('readings').children[0].children[4].children[0].textContent,'-4s ±2s');
 console.log('PASS: guest controls, state access and client mutation guard; admin controls enabled');
})().catch(e=>{console.error(e);process.exitCode=1});