from pathlib import Path
import os,subprocess,tempfile
root=Path(__file__).resolve().parents[2]
src=root/'vendor/MeshCore'
s=(src/'src/helpers/BaseChatMesh.cpp').read_text();h=(src/'src/helpers/BaseChatMesh.h').read_text()
a=s.index('int  BaseChatMesh::sendMessage(');b=s.index('int  BaseChatMesh::sendCommandData(',a);dm=s[a:b]
a=s.index('bool BaseChatMesh::sendGroupMessage(');b=s.index('bool BaseChatMesh::sendGroupData(',a);group=s[a:b]
declarations='\n'.join(l.strip() for l in h.splitlines() if ' sendMessage(' in l or ' sendGroupMessage(' in l)
source='#include <cstdint>\n#include <cstring>\n#include <cstdio>\n#include <cassert>\n#define OUT_PATH_UNKNOWN 255\n#define MSG_SEND_FAILED 0\n#define MSG_SEND_SENT_FLOOD 1\n#define MSG_SEND_SENT_DIRECT 2\n#define MAX_TEXT_LEN 160\n#define PAYLOAD_TYPE_GRP_TXT 1\nnamespace mesh {struct Packet{int getRawLength(){return 40;}};struct GroupChannel{};}\nstruct ContactInfo{uint8_t out_path[32]{};uint8_t out_path_len=255;};\nstruct BaseChatMesh {\n struct Radio{uint32_t getEstAirtimeFor(int){return 100;}}radio;Radio* _radio=&radio;\n mesh::Packet packet;bool fail=false;unsigned sends=0;uint32_t queuedDelay=0,txt_send_timeout=0;\n mesh::Packet* composeMsgPacket(const ContactInfo&,uint32_t,uint8_t,const char*,uint32_t& ack){ack=42;return fail?nullptr:&packet;}\n mesh::Packet* createGroupDatagram(int,mesh::GroupChannel&,const uint8_t*,int){return fail?nullptr:&packet;}\n void sendFloodScoped(const ContactInfo&,mesh::Packet*,uint32_t d){++sends;queuedDelay=d;}\n void sendFloodScoped(mesh::GroupChannel&,mesh::Packet*,uint32_t d){++sends;queuedDelay=d;}\n void sendDirect(mesh::Packet*,const uint8_t*,uint8_t,uint32_t d){++sends;queuedDelay=d;}\n uint32_t calcFloodTimeoutMillisFor(uint32_t){return 5000;}\n uint32_t calcDirectTimeoutMillisFor(uint32_t,uint8_t){return 2000;}\n uint32_t futureMillis(uint32_t delay){return 1000+delay;}\n'+declarations+"\n};\n"+dm+group+'int main(){\n BaseChatMesh m;ContactInfo c;uint32_t ack=0,timeout=0;\n assert(m.sendMessage(c,1,0,"Reply",ack,timeout,300)==MSG_SEND_SENT_FLOOD);\n assert(m.queuedDelay==300 && timeout==5300 && m.txt_send_timeout==6300);\n c.out_path_len=2;assert(m.sendMessage(c,2,0,"Reply",ack,timeout,300)==MSG_SEND_SENT_DIRECT);\n assert(m.queuedDelay==300 && timeout==2300 && m.txt_send_timeout==3300);\n assert(m.sendMessage(c,2,1,"Retry",ack,timeout,300)==MSG_SEND_SENT_DIRECT);assert(m.queuedDelay==300);\n m.sendMessage(c,3,0,"Ordinary companion",ack,timeout);assert(m.queuedDelay==0 && timeout==2000);\n mesh::GroupChannel channel;assert(m.sendGroupMessage(4,channel,"Bot","Reply",5,300));assert(m.queuedDelay==300);\n assert(m.sendGroupMessage(4,channel,"User","Message",7));assert(m.queuedDelay==0);\n m.fail=true;const auto before=m.sends;assert(m.sendMessage(c,5,0,"Reply",ack,timeout,300)==MSG_SEND_FAILED);\n assert(!m.sendGroupMessage(5,channel,"Bot","Reply",5,300));assert(m.sends==before);\n}\n'
with tempfile.TemporaryDirectory() as d:
 cpp=Path(d)/'test.cpp';exe=Path(d)/'test.exe';cpp.write_text(source)
 subprocess.run([os.environ.get('CXX','g++'),'-std=c++11',str(cpp),'-o',str(exe)],check=True)
 subprocess.run([str(exe)],check=True)
print('PASS response queue delay for direct/flood/channel packets, ACK allowance, retries and default sends')
